//HintName: MainWindow.g.cs
// <auto-generated />
// Source: MainWindow.axaml
// Lines: 19
// DataType sections detected: 1
//   DataType: SomeDataType at Window -> 6 binding-like attributes
//     TextBlock.Text = {Binding ServiceTitle}
//     TextBlock.Text = {Binding ServerName, StringFormat='with {0}'}
//     TextBlock.Text = {Binding ServiceDateTime, StringFormat={}{0:dd MMM yyyy}}
//     TextBlock.Text = {Binding ServiceDateTime, StringFormat={}{0:HH:mm}}
//     TextBlock.Text = {Binding ServicePrice, StringFormat={}{0:£0.00}}
//     TextBlock.Text = {Binding Description, StringFormat={}{0:£0.00}}
using System;

namespace DesignTimeDataGenerator.Generated
{
    public partial class MainWindow
    {
    }
}
